'use client';

import React, { useState, useCallback, useEffect, useRef, useMemo } from 'react';
import { FontPairing, ColorPalette } from '@/lib/schemas';
import { memorySystem } from '@/lib/memory';
import TypographyPreview from './TypographyPreview';
import LikeBar from './LikeBar';
import { Unlock, Lock, UserPlus } from 'lucide-react';
import { useSession } from 'next-auth/react';
import Link from 'next/link';

type Category = 'serif' | 'sans-serif' | 'handwriting' | 'display';
type TabType = 'fonts' | 'colors';

interface GeneratorPanelProps {
    className?: string;
    memories?: any[];
    setMemories?: (m: any[]) => void;
    isMemoriesOpen?: boolean;
    setIsMemoriesOpen?: (v: boolean) => void;
}

export default function GeneratorPanel({
                                           className = '',
                                       }: GeneratorPanelProps) {
    const { data: session } = useSession();

    // --- State (functionality from the first file) ---
    const [activeTab] = useState<TabType>('fonts'); // kept for parity; UI doesn’t render tabs
    const [currentFont, setCurrentFont] = useState<FontPairing | null>(null);
    const [currentPalette, setCurrentPalette] = useState<ColorPalette | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const ALL_CATEGORIES: Category[] = ['serif', 'sans-serif', 'handwriting', 'display'];

    // Locks (fonts + colors)
    const [lockPrimaryFont, setLockPrimaryFont] = useState(false);
    const [lockSecondaryFont, setLockSecondaryFont] = useState(false);
    const [lockPrimaryColor, setLockPrimaryColor] = useState(false);
    const [lockSecondaryColor, setLockSecondaryColor] = useState(false);
    const [lockAccentColor, setLockAccentColor] = useState(false);

    const [primaryCategories, setPrimaryCategories] = useState<Category[]>(['serif', 'sans-serif']);
    const [secondaryCategories, setSecondaryCategories] = useState<Category[]>(['serif', 'sans-serif']);

    const toggleIn = (arr: Category[], v: Category) =>
        arr.includes(v) ? arr.filter((x) => x !== v) : [...arr, v];

    const hasAutoGenerated = useRef(false);

    // --- Generator function (shared) ---
    const generateDesign = useCallback(
        async (type: 'fonts' | 'colors', options: any = {}) => {
            setError(null);
            try {
                const liked = memorySystem.getLikedItems();
                const response = await fetch('/api/design', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        type: type === 'fonts' ? 'font' : 'color',
                        options,
                        memories: liked,
                    }),
                });
                if (!response.ok) {
                    const body = await response.text();
                    throw new Error(`HTTP ${response.status}: ${body}`);
                }
                const result = await response.json();
                if (!result?.data) throw new Error(`No data returned for ${type}`);
                return result.data;
            } catch (err) {
                const msg = err instanceof Error ? err.message : 'An error occurred';
                setError(msg);
                console.error(`Generation error for ${type}:`, err);
                return null;
            }
        },
        []
    );

    const buildFontOptions = useCallback(
        () => ({
            primaryCategories,
            secondaryCategories,
            ...(currentFont && (lockPrimaryFont || lockSecondaryFont)
                ? {
                    locked: {
                        ...(lockPrimaryFont
                            ? { primaryName: currentFont.primary.name, primaryWeight: currentFont.primary.weight }
                            : {}),
                        ...(lockSecondaryFont
                            ? { secondaryName: currentFont.secondary.name, secondaryWeight: currentFont.secondary.weight }
                            : {}),
                    },
                }
                : {}),
        }),
        [currentFont, primaryCategories, secondaryCategories, lockPrimaryFont, lockSecondaryFont]
    );

    const generateBoth = useCallback(async () => {
        setIsLoading(true);
        setError(null);
        try {
            // Fonts
            const fontOptions = buildFontOptions();
            const newFont = await generateDesign('fonts', fontOptions);
            if (newFont) {
                setCurrentFont((prev) => ({
                    primary: lockPrimaryFont ? prev?.primary : newFont.primary,
                    secondary: lockSecondaryFont ? prev?.secondary : newFont.secondary,
                }) as FontPairing);
            }

            // Colors
            const newPalette = await generateDesign('colors', {});
            if (newPalette) {
                setCurrentPalette((prev) => ({
                    primary: lockPrimaryColor ? prev?.primary : newPalette.primary,
                    secondary: lockSecondaryColor ? prev?.secondary : newPalette.secondary,
                    accent: lockAccentColor ? prev?.accent : newPalette.accent,
                }) as ColorPalette);
            }
        } catch (err) {
            const msg = err instanceof Error ? err.message : 'An error occurred';
            console.error('Generate both error:', err);
            setError(msg);
        } finally {
            setIsLoading(false);
<<<<<<< Updated upstream
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
        }
    }, [
        generateDesign,
        buildFontOptions,
        lockPrimaryFont,
        lockSecondaryFont,
        lockPrimaryColor,
        lockSecondaryColor,
        lockAccentColor,
    ]);
<<<<<<< Updated upstream
            // Colors
            const newPalette = await generateDesign('colors', {});
            if (newPalette) {
                setCurrentPalette((prev) => ({
                    primary: lockPrimaryColor ? prev?.primary : newPalette.primary,
                    secondary: lockSecondaryColor ? prev?.secondary : newPalette.secondary,
                    accent: lockAccentColor ? prev?.accent : newPalette.accent,
                }) as ColorPalette);
            }
        } catch (err) {
            const msg = err instanceof Error ? err.message : 'An error occurred';
            console.error('Generate both error:', err);
            setError(msg);
        } finally {
            setIsLoading(false);
        }
    }, [
        generateDesign,
        buildFontOptions,
        lockPrimaryFont,
        lockSecondaryFont,
        lockPrimaryColor,
        lockSecondaryColor,
        lockAccentColor,
    ]);
=======
>>>>>>> Stashed changes

    // Spacebar to generate
    useEffect(() => {
        const handler = (e: KeyboardEvent) => {
            const t = e.target as HTMLElement | null;
            const isTyping =
                t?.isContentEditable ||
                t?.tagName === 'INPUT' ||
                t?.tagName === 'TEXTAREA' ||
                t?.tagName === 'SELECT';
            if (isTyping) return;
            if (e.code === 'Space') {
                e.preventDefault();
                if (!isLoading) generateBoth();
            }
        };
        window.addEventListener('keydown', handler);
        return () => window.removeEventListener('keydown', handler);
    }, [isLoading, generateBoth]);

    // Auto-generate once
    useEffect(() => {
        if (hasAutoGenerated.current) return;
        hasAutoGenerated.current = true;
        if (!currentFont || !currentPalette) generateBoth();
    }, [generateBoth, currentFont, currentPalette]);

    // Like/save current selection(s) — includes combo save from the first file
    const handleLike = useCallback(async () => {
        const userEmail = session?.user?.email;
        if (!userEmail) {
            console.error('No logged-in user email found');
            return;
        }

        // Save font
        if (currentFont) {
            const fontMemory = memorySystem.createMemoryFromData('font', currentFont);
            memorySystem.saveMemory(fontMemory);
            memorySystem.saveFeedback(memorySystem.createFeedbackFromMemory(fontMemory, 'like'));

            try {
                const res = await fetch('/api/save/fonts', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ ...currentFont, email: userEmail }),
                });
                const result = await res.json();
                if (!res.ok) throw new Error(result?.error || 'Failed to save font');
            } catch (err) {
                console.error('Font save error:', err);
            }
        }

        // Save colors (with primary/secondary/accent values)
        if (currentPalette?.primary?.value && currentPalette?.secondary?.value && currentPalette?.accent?.value) {
            const colorData = {
                email: userEmail,
                case_id: Date.now().toString(),
                primary: currentPalette.primary.value,
                secondary: currentPalette.secondary.value,
                accent: currentPalette.accent.value,
            };

            const colorMemory = memorySystem.createMemoryFromData('color', colorData);
            memorySystem.saveMemory(colorMemory);
            memorySystem.saveFeedback(memorySystem.createFeedbackFromMemory(colorMemory, 'like'));

            try {
                const res = await fetch('/api/save/colors', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(colorData),
                });
                const result = await res.json();
                if (!res.ok) throw new Error(result?.error || 'Failed to save color');
            } catch (err) {
                console.error('Color save error:', err);
            }
        }

        // Save combo (font + full color trio) — from first file
        if (currentFont && currentPalette?.primary && currentPalette?.secondary && currentPalette?.accent) {
            try {
                const colorPair = {
                    case_id: Date.now().toString(),
                    primary: {
                        name: 'Primary',
                        value: currentPalette.primary.value,
                        contrast: currentPalette.primary.contrast ?? '#000000',
                    },
                    secondary: {
                        name: 'Secondary',
                        value: currentPalette.secondary.value,
                        contrast: currentPalette.secondary.contrast ?? '#000000',
                    },
                    accent: {
                        name: 'Accent',
                        value: currentPalette.accent.value,
                        contrast: currentPalette.accent.contrast ?? '#000000',
                    },
                };
                const fontPair = {
                    case_id: (Date.now() + 1).toString(),
                    primary: currentFont.primary,
                    secondary: currentFont.secondary,
                };
                const res = await fetch('/api/save/combos', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ colorPair, fontPair }),
                });
                const result = await res.json();
                if (!res.ok) throw new Error(result?.error || 'Failed to save combo');
            } catch (err) {
                console.error('Combo save error:', err);
            }
        }
    }, [currentFont, currentPalette, session]);

    // Derived display colors
    const colors = useMemo(
        () => ({
            primary: currentPalette?.primary?.value ?? '#111111',
            secondary: currentPalette?.secondary?.value ?? '#374151',
            accent: currentPalette?.accent?.value ?? '#2563eb',
        }),
        [currentPalette]
    );

    // --- Render (uses the second file’s look-and-feel) ---
    const renderContent = () => (
        <div className="space-y-6">

            {!session && (
                <div className="mb-2 rounded-lg border border-bg bg-white p-4">
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <UserPlus className="w-5 h-5 text-ink" />
                            <div>
                                <h4 className="font-outfit text-sm md:text-base font-medium text-ink">
                                    Track Your Design Preferences
                                </h4>
                                <p className="text-xs text-ink/80">
                                    Sign up to let the AI learn your style and create personalized designs.
                                </p>
                            </div>
                        </div>
                        <Link href="/accounts">
                            <button className="px-4 py-2 rounded-md font-outfit text-sm bg-ink text-foreground hover:opacity-90 transition">
                                Track Preferences
                            </button>
                        </Link>
                    </div>
                </div>
            )}

            <h4 className="font-outfit text-left text-sm md:text-base font-medium text-ink/80">
                Press spacebar to generate themes!
            </h4>

            {/* Color cards with locks (styled like the second file) */}
            <div className="grid grid-cols-3 gap-3">
                {([
                    { key: 'primary' as const, label: 'Primary', val: colors.primary, locked: lockPrimaryColor, toggle: () => setLockPrimaryColor((v) => !v) },
                    { key: 'secondary' as const, label: 'Secondary', val: colors.secondary, locked: lockSecondaryColor, toggle: () => setLockSecondaryColor((v) => !v) },
                    { key: 'accent' as const, label: 'Accent', val: colors.accent, locked: lockAccentColor, toggle: () => setLockAccentColor((v) => !v) },
                ]).map(({ key, label, val, locked, toggle }) => (
                    <div key={key} className="bg-white rounded-md border border-gray-200 overflow-hidden font-ui text-ink">
                        <div style={{ background: val, height: 48 }} />
                        <div className="p-2 text-sm flex items-center justify-between">
                            <div className="flex items-center gap-2">
                                <span className="font-medium">{label}</span>
                                <button
                                    type="button"
                                    aria-pressed={locked}
                                    onClick={toggle}
                                    className="inline-flex items-center gap-2 px-3 py-1.5 text-sm text-ink"
                                    title={locked ? 'Unlock' : 'Lock'}
                                >
                                    {locked ? <Lock className="h-3.5 w-3.5" /> : <Unlock className="h-3.5 w-3.5" />}
                                </button>
                            </div>
                            <code className="text-gray-600">{val}</code>
                        </div>
                    </div>
                ))}
            </div>

            <TypographyPreview fontPairing={currentFont} palette={currentPalette} />

            {/* Controls card (second file styling) */}
            <div className="rounded-2xl border border-bg bg-nav-surface p-6 shadow-sm">
                <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
                    {/* Primary Font */}
                    <div>
                        <div className="mb-3 flex items-center gap-1">
              <span className="font-outfit text-sm font-medium leading-none text-ink/90">
                Primary Font
              </span>
                            <button
                                type="button"
                                onClick={() => setLockPrimaryFont((v) => !v)}
                                aria-pressed={lockPrimaryFont}
                                className="inline-flex items-center gap-2 px-3 py-1.5 text-sm text-ink"
                            >
                                {lockPrimaryFont ? <Lock className="h-4 w-4" /> : <Unlock className="h-4 w-4" />}
                            </button>
                        </div>

                        <div className="flex flex-wrap gap-3">
                            {ALL_CATEGORIES.map((cat) => (
                                <label
                                    key={`prim-${cat}`}
                                    className="inline-flex items-center gap-2 rounded-full bg-white /60 px-3 py-1.5 font-outfit text-sm capitalize text-ink/80 border border-bg"
                                >
                                    <input
                                        type="checkbox"
                                        className="h-4 w-4 rounded-sm checkbox-ink focus:ring-2 focus:ring-[color:var(--ink)]/30"
                                        checked={primaryCategories.includes(cat)}
                                        onChange={() => setPrimaryCategories((c) => toggleIn(c, cat))}
                                        disabled={lockPrimaryFont}
                                    />
                                    <span>{cat.replace('-', ' ')}</span>
                                </label>
                            ))}
                        </div>
                    </div>

                    {/* Secondary Font */}
                    <div>
                        <div className="mb-3 flex items-center gap-1">
              <span className="font-outfit text-sm font-medium leading-none text-ink/90">
                Secondary Font
              </span>
                            <button
                                type="button"
                                onClick={() => setLockSecondaryFont((v) => !v)}
                                aria-pressed={lockSecondaryFont}
                                className="inline-flex items-center gap-2 px-3 py-1.5 text-sm text-ink"
                            >
                                {lockSecondaryFont ? <Lock className="h-4 w-4" /> : <Unlock className="h-4 w-4" />}
                            </button>
                        </div>

                        <div className="flex flex-wrap gap-3">
                            {ALL_CATEGORIES.map((cat) => (
                                <label
                                    key={`sec-${cat}`}
                                    className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-1.5 font-outfit text-sm capitalize text-ink/80 border border-bg"
                                >
                                    <input
                                        type="checkbox"
                                        className="h-4 w-4 rounded-sm checkbox-ink focus:ring-2 focus:ring-[color:var(--ink)]/30"
                                        checked={secondaryCategories.includes(cat)}
                                        onChange={() => setSecondaryCategories((c) => toggleIn(c, cat))}
                                        disabled={lockSecondaryFont}
                                    />
                                    <span>{cat.replace('-', ' ')}</span>
                                </label>
                            ))}
                        </div>
                    </div>
                </div>
            </div>

            {(currentFont || currentPalette) && <LikeBar onLike={handleLike} />}
        </div>
    );

    return (
        <div className={`bg-light rounded-lg shadow-lg ${className}`}>
            <div className="p-6">
                {error && (
                    <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-md">
                        <p className="text-red-600 text-sm">{error}</p>
                    </div>
                )}
                {renderContent()}
            </div>
        </div>
    );
}
