'use client';

import React, { useState, useCallback, useEffect, useRef } from 'react';
import { FontPairing, ColorPalette, Component, MemoryItem } from '@/lib/schemas';
import { memorySystem } from '@/lib/memory';
import TypographyPreview from './TypographyPreview';
import LikeBar from './LikeBar';
import { Palette, Type, Component as ComponentIcon, Unlock, Lock} from 'lucide-react';
import { useSession } from 'next-auth/react';

type TabType = 'fonts' | 'colors' | 'components';
type Category = 'serif' | 'sans-serif' | 'handwriting' | 'display';

interface GeneratorPanelProps {
  className?: string;
  memories?: MemoryItem[];
  setMemories?: (memories: MemoryItem[]) => void;
  isMemoriesOpen?: boolean;
  setIsMemoriesOpen?: (open: boolean) => void;
}

export default function GeneratorPanel({ 
  className = '',
  memories = [],
  setMemories,
  isMemoriesOpen = false,
  setIsMemoriesOpen
}: GeneratorPanelProps) {
  const [currentFont, setCurrentFont] = useState<FontPairing | null>(null);
  const [currentPalette, setCurrentPalette] = useState<ColorPalette | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const ALL_CATEGORIES: Category[] = ['serif','sans-serif','handwriting','display'];

  // --- Locks ---
  const [lockPrimaryFont, setLockPrimaryFont] = useState(false);
  const [lockSecondaryFont, setLockSecondaryFont] = useState(false);
  const [lockPrimaryColor, setLockPrimaryColor] = useState(false);
  const [lockSecondaryColor, setLockSecondaryColor] = useState(false);
  const [lockAccentColor, setLockAccentColor] = useState(false);

  const [primaryCategories, setPrimaryCategories] = useState<Category[]>(['serif','sans-serif']);
  const [secondaryCategories, setSecondaryCategories] = useState<Category[]>(['serif','sans-serif']);

  const toggleIn = (arr: Category[], v: Category) =>
    arr.includes(v) ? arr.filter(x => x !== v) : [...arr, v];

  const { data: session } = useSession();
  const hasAutoGenerated = useRef(false);

  // --- Generator function ---
  const generateDesign = useCallback(async (type: TabType, options: any = {}) => {
    setError(null);
    try {
      const memories = memorySystem.getLikedItems();
      const response = await fetch('/api/design', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: type === 'fonts' ? 'font' : type === 'colors' ? 'color' : 'component', options, memories }),
      });
      if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
      const result = await response.json();
      return result.data;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
      console.error('Generation error:', err);
      return null;
    }
  }, []);

  const buildFontOptions = useCallback(() => ({
    primaryCategories,
    secondaryCategories,
    ...(currentFont && (lockPrimaryFont || lockSecondaryFont)
      ? {
          locked: {
            ...(lockPrimaryFont ? { primaryName: currentFont.primary.name, primaryWeight: currentFont.primary.weight } : {}),
            ...(lockSecondaryFont ? { secondaryName: currentFont.secondary.name, secondaryWeight: currentFont.secondary.weight } : {}),
          }
        }
      : {}),
  }), [currentFont, primaryCategories, secondaryCategories, lockPrimaryFont, lockSecondaryFont]);

  const generateBoth = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      // Fonts
      const fontOptions = buildFontOptions();
      const newFont = await generateDesign('fonts', fontOptions);
      if (newFont) {
        setCurrentFont(prev => ({
          primary:   lockPrimaryFont   ? prev?.primary   : newFont.primary,
          secondary: lockSecondaryFont ? prev?.secondary : newFont.secondary,
        }));
      }

      // Colors
      const newPalette = await generateDesign('colors', {});
      if (newPalette) {
        setCurrentPalette(prev => ({
          primary:   lockPrimaryColor   ? prev?.primary   : newPalette.primary,
          secondary: lockSecondaryColor ? prev?.secondary : newPalette.secondary,
          accent:    lockAccentColor    ? prev?.accent    : newPalette.accent,
        }));
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setIsLoading(false);
    }
  }, [generateDesign, buildFontOptions, lockPrimaryFont, lockSecondaryFont, lockPrimaryColor, lockSecondaryColor, lockAccentColor]);

  // --- Spacebar generation ---
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      const t = e.target as HTMLElement | null;
      const tag = t?.tagName;
      const isTyping = t?.isContentEditable || tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT';
      if (isTyping) return;
      if (e.code === 'Space') {
        e.preventDefault();
        if (!isLoading) generateBoth();
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [isLoading, generateBoth]);

  // --- Auto-generate on first render ---
  useEffect(() => {
    if (hasAutoGenerated.current) return;
    hasAutoGenerated.current = true;
    if (!currentFont || !currentPalette) generateBoth();
  }, [generateBoth, currentFont, currentPalette]);

  // --- Handle Likes ---
  const handleLike = useCallback(async () => {
    const userEmail = session?.user?.email;
    if (!userEmail) return console.error("No logged-in user email found");

    // Save font
    if (currentFont) {
      const fontMemory = memorySystem.createMemoryFromData('font', currentFont);
      const fontFeedback = memorySystem.createFeedbackFromMemory(fontMemory, 'like');
      memorySystem.saveMemory(fontMemory);
      memorySystem.saveFeedback(fontFeedback);
      try {
        const res = await fetch('/api/save/fonts', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ...currentFont, email: userEmail }),
        });
        const result = await res.json();
        if (!res.ok) throw new Error(result.error || 'Failed to save font');
        console.log('Font saved:', result);
      } catch (err) {
        console.error('Font save error:', err);
      }
    }

    // Save colors
    if (currentPalette) {
      const colorData = {
        email: userEmail,
        case_id: Date.now().toString(),
        color: currentPalette.primary.value,
        color2: currentPalette.secondary.value,
        accent: currentPalette.accent.value,
      };
      const colorMemory = memorySystem.createMemoryFromData('color', colorData);
      const colorFeedback = memorySystem.createFeedbackFromMemory(colorMemory, 'like');
      memorySystem.saveMemory(colorMemory);
      memorySystem.saveFeedback(colorFeedback);
      try {
        const res = await fetch('/api/save/colors', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(colorData),
        });
        const result = await res.json();
        if (!res.ok) throw new Error(result.error || 'Failed to save color');
        console.log('Color saved:', result);
      } catch (err) {
        console.error('Color save error:', err);
      }
    }
  }, [currentFont, currentPalette, session]);

  // --- Render ---
  const renderContent = () => (
    <div className="space-y-6">
      <div className="mb-6 rounded-lg border border-gray-200 bg-white p-6">
        <h4 className="mb-3 text-base font-semibold text-gray-800 text-left">
          Press the spacebar to generate themes!
        </h4>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Font One */}
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-sm font-medium text-gray-700">Font One</span>
              <button type="button" onClick={() => setLockPrimaryFont(v => !v)} className="inline-flex items-center gap-2 px-3 py-1.5 text-sm text-gray-700">
                {lockPrimaryFont ? <Lock className="h-4 w-4" /> : <Unlock className="h-4 w-4" />}
              </button>
            </div>
            <div className="flex gap-4 flex-wrap">
              {ALL_CATEGORIES.map(cat => (
                <label key={`prim-${cat}`} className="inline-flex items-center gap-2 text-sm text-gray-700">
                  <input
                    type="checkbox"
                    className="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-2 focus:ring-blue-500 focus:ring-offset-0"
                    checked={primaryCategories.includes(cat)}
                    onChange={() => setPrimaryCategories(c => toggleIn(c, cat))}
                    disabled={lockPrimaryFont}
                  />
                  <span className="capitalize">{cat}</span>
                </label>
              ))}
            </div>
          </div>

          {/* Font Two */}
          <div>
            <div className="flex items-center gap-2 mb-2 justify-end">
              <span className="text-sm font-medium text-gray-700">Font Two</span>
              <button type="button" onClick={() => setLockSecondaryFont(v => !v)} className="inline-flex items-center gap-2 px-3 py-1.5 text-sm text-gray-700">
                {lockSecondaryFont ? <Lock className="h-4 w-4" /> : <Unlock className="h-4 w-4" />}
              </button>
            </div>
            <div className="flex gap-4 flex-wrap justify-end">
              {ALL_CATEGORIES.map(cat => (
                <label key={`sec-${cat}`} className="inline-flex items-center gap-2 text-sm text-gray-700">
                  <input
                    type="checkbox"
                    className="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-2 focus:ring-blue-500 focus:ring-offset-0"
                    checked={secondaryCategories.includes(cat)}
                    onChange={() => setSecondaryCategories(c => toggleIn(c, cat))}
                    disabled={lockSecondaryFont}
                  />
                  <span className="capitalize">{cat}</span>
                </label>
              ))}
            </div>
          </div>
        </div>

        {/* Color Locks */}
        <div className="flex gap-6 mt-6">
          {['Primary', 'Secondary', 'Accent'].map((label, idx) => {
            const lockState = idx === 0 ? lockPrimaryColor : idx === 1 ? lockSecondaryColor : lockAccentColor;
            const toggle = idx === 0 ? setLockPrimaryColor : idx === 1 ? setLockSecondaryColor : setLockAccentColor;
            return (
              <div key={label} className="flex items-center gap-2">
                <span className="text-sm font-medium text-gray-700">{label}</span>
                <button type="button" onClick={() => toggle(v => !v)} className="inline-flex items-center gap-2 px-3 py-1.5 text-sm text-gray-700">
                  {lockState ? <Lock className="h-4 w-4" /> : <Unlock className="h-4 w-4" />}
                </button>
              </div>
            );
          })}
        </div>
      </div>

      <TypographyPreview fontPairing={currentFont} palette={currentPalette} />
      {(currentFont || currentPalette) && <LikeBar onLike={handleLike} />}
    </div>
  );

  return (
    <div className={`bg-light rounded-lg shadow-lg ${className}`}>
      <div className="p-6">
        {error && (
          <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-md">
            <p className="text-red-600 text-sm">{error}</p>
          </div>
        )}
        {renderContent()}
      </div>
    </div>
  );
}
